# Generated by Django 4.0.3 on 2022-03-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в телеграмме')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Предпочтение')),
            ],
            options={
                'verbose_name': 'Предпочтение',
                'verbose_name_plural': 'Предпочтения',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('paid_until', models.DateField()),
                ('person_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество персон')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.customer', verbose_name='Подписка')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.preference', verbose_name='Предпочтение')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество ингредиента')),
                ('ingredient_measure', models.CharField(max_length=30, verbose_name='Единица измерения')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeClassificator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.preference')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='tg_food_plan_bot.RecipeIngredient', to='tg_food_plan_bot.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preferences',
            field=models.ManyToManyField(through='tg_food_plan_bot.RecipeClassificator', to='tg_food_plan_bot.preference'),
        ),
    ]
